version: "3.9"
services:
  portainer:
      image: portainer/portainer-ce:latest
      container_name: portainer
      env_file: .env
      environment:
            - PUID=${puid}
            - PGID=${guid}
            - TZ=$tzone
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer-data:/data 
      ports:
        - 8000:8000
        - 9443:9443
      restart: always
volumes:
  portainer-data:
    external: true
networks:
    private:
        external: true